name: Check code health

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Run Svelte diagnostics checks
        run: npm run check
      - name: Run Prettier & ESLint
        run: npm run lint
  test:
    runs-on: ${{ matrix.os }}
    needs: [check]
    if: needs.check.result == 'success'
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Run the integration tests
        run: npx playwright install && npm run test:integration
      - name: Run the unit tests
        run: npm run test:unit
  update-badges:
    runs-on: ${{ matrix.os }}
    needs: [test]
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [latest]
    steps:
      - name: Update tests badge
        if: needs.test.result == 'success'
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
          auth: ${{ secrets.BADGE_GIST_SECRET }}
          gistID: 0cfdce04c9451b3a6ed64465a24a3811
          filename: tests.json
          label: Tests
          message: passing
          color: green
      - name: Update Version Badge
        if: needs.test.result == 'success'
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
          auth: ${{ secrets.BADGE_GIST_SECRET }}
          gistID: ee16590d968b028997b7fcb70337bb23
          filename: version.json
          label: Version
          message: ${{ github.ref }}
          color: blue
