name: Check code health

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [lts, latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Setup pnpm and install dependencies
        uses: pnpm/setup@v2
        with:
          version: ^12.0
          runtime: node@${{ matrix.node-version }}
          cache: true
      - name: Run Svelte diagnostics checks
        run: pnpm check
      - name: Run Prettier & ESLint
        run: pnpm lint
  test:
    runs-on: ${{ matrix.os }}
    needs: [check]
    if: needs.check.result == 'success'
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [lts, latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Setup pnpm and install dependencies
        uses: pnpm/setup@v2
        with:
          version: ^12.0
          runtime: node@${{ matrix.node-version }}
          cache: true
      - name: Run the integration tests
        run: npx playwright install && pnpm test:integration
      - name: Run the unit tests
        run: pnpm test:unit
  update-badges:
    runs-on: ${{ matrix.os }}
    needs: [test]
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [lts, latest]
    steps:
      - name: Update tests badge
        if: needs.test.result == 'success'
        uses: schneegans/dynamic-badges-action@v1.9.0
        with:
          auth: ${{ secrets.BADGE_GIST_SECRET }}
          gistID: 0cfdce04c9451b3a6ed64465a24a3811
          filename: tests.json
          label: Tests
          message: passing
          color: green
      - name: Update Version Badge
        if: needs.test.result == 'success'
        uses: schneegans/dynamic-badges-action@v1.9.0
        with:
          auth: ${{ secrets.BADGE_GIST_SECRET }}
          gistID: ee16590d968b028997b7fcb70337bb23
          filename: version.json
          label: Version
          message: ${{ github.ref }}
          color: blue
